#!C:/Program\ Files/Git/usr/bin/sh.exe


echo "*******************************"
echo "Running git pre-commit hook"
echo "*******************************"

./gradlew app:ktlintCheck --daemon

RESULT=$?

# return 1 exit code if running checks fails
[ $RESULT -ne 0 ] && exit 1
exit 0